podTemplate(
    label: 'mypod', 
    inheritFrom: 'default',
    containers: [
        containerTemplate(
            name: 'docker', 
            image: 'docker:18.02',
            ttyEnabled: true,
            command: 'cat'
        )
    ],
    volumes: [
        hostPathVolume(
            hostPath: '/var/run/docker.sock',
            mountPath: '/var/run/docker.sock'
        )
    ]
) {
    node('mypod') {
        stage ('Extract') {
            checkout scm
        }
        stage ('Docker') {
            container ('docker') {
                sh "docker build -t myimage:latest ."
                sh "docker images"
            }
        }
    }
}